name: robtop
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - boost=1.78.0
  - boost-cpp=1.78.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - cgal=5.5.2
  - cgal-cpp=5.5.2
  - eigen=3.4.0
  - freeglut=3.2.2
  - gflags=2.2.2
  - glm=0.9.9.8
  - icu=72.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsqlite=3.42.0
  - libxcb=1.15
  - libzlib=1.2.13
  - mpfr=4.2.0
  - numpy=1.24.3
  - openssl=3.1.1
  - pip=23.1.2
  - pthread-stubs=0.4
  - python=3.11.3
  - python_abi=3.11
  - rapidjson=1.1.0
  - setuptools=67.7.2
  - tbb=2018.0.5
  - tbb-devel=2018.0.5
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.40.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zstd=1.5.2
